# Generated by Django 4.2.7 on 2026-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('technology', 'Technology'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science'), ('world', 'World'), ('other', 'Other')], default='other', max_length=50)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('authenticity', models.CharField(choices=[('real', 'Real'), ('fake', 'Fake'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence score (0-1)', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-scraped_date'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('fake', 'Fake'), ('real', 'Real')], max_length=10)),
                ('confidence_score', models.FloatField(help_text='Model confidence score (0-1)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
